### ISSUE TITLE
Line Number Commands

### ISSUE THREAD

**Issue by EoghanOfLight** [scottmwyant/vscode-gcode#2]
I'm getting an error trying to use the line number commands. both .addlinenumbers and .removelinenumbers produces an error and no changes are made. not sure if this is enough information for you, let me know if i can be more specific.

**Comment by scottmwyant** [comment]
@EoghanOfLight, I've just spent a couple minutes looking at this.  It's working for me, with the sample code I have.  I'm going to need a little more information to troubleshoot this.  What are you seeing that indicates an error?  Is there an error message?  Could you provide a screenshot?

Here's a test you can do.  Copy the content of the [sample.nc](https://raw.githubusercontent.com/scottmwyant/vscode-gcode/master/.vscode/sample.nc) file from my repository.  Save that content into a new file on your system and run the commands on that file.  If the behavior is different than what you see in your own program, I'd be interested to see your code.  You may have something going on in your program that I haven't thought of / guarded against.

Scott
