### ISSUE TITLE
saving files as .TXT .TAP or .NC

### ISSUE THREAD

**Issue by DeeMadmachinist** [scottmwyant/vscode-gcode#5]
How do we get this to save the files as .txt or .Tap and maintain all teh benefits of this wonderful G code viewer and editor.  Whenever I enter the file in a format that my mach4 accepts it doesn't give me color coding or any of the benefits of using this extension.  Thanks for this extension.  Will save me a ton of time numbering the lines when I have to edit visually looking for a color to find things like Z X or Y also a tremendous time saver.  THANKS.

**Comment by scottmwyant** [comment]
The easiest way to accomplish what you want is to configure VS Code.

Some background:

My extension adds "language support". Every extension that does this must specify what language it supports using an identifier, for example, `python`. I couldn't find a commonly used identifier for CNC G-code files, I elected to use simply `gcode`. 

You need to make VS Code associate `.txt` and `.tap` files (and whatever else) with my `gcode` language identifier.

There are various ways to do this. Check out this SO answer and let me know if it's not clear. 

https://stackoverflow.com/a/51228725

You happened to catch me at the right moment, I haven't thought about this project in a few years. Glad you are finding it useful.

Cheers!

**Comment by DeeMadmachinist** [comment]
Don’t  know how to say thank you.  So basically change language mode  takes any file and applies the G code trimmings to it.  That does it now I know how to use VS and your extension to do exactlky what I need with total ease.  Thanks
